# Forzar el uso de Wayland puro
--ozone-platform-hint=x11
--disable-gpu
--disable-accelerated-2d-canvas


# SOLUCIÓN AL PIXELADO: Desactiva el renderizado inestable de GPU
--disable-gpu-rasterization
--disable-gpu-compositing
--disable-software-rasterizer

# SOLUCIÓN A ERRORES DE COLOR Y WAYLAND:
--force-color-profile=srgb
--disable-features=WaylandColorManagement,WaylandFractionalScaleV1

# SOLUCIÓN A LOS ERRORES DE TERMINAL (LOGS):
--log-level=3
--v=-1
--gcm-checkin-url=http://0.0.0.0
--gcm-mcs-endpoint=http://0.0.0.0
